# Generated by Django 4.0.5 on 2022-06-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devinfo.tag')),
            ],
        ),
    ]
