# Generated by Django 4.0.5 on 2022-06-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinfo', '0002_remove_tag_children_tag_thumbnail_tagrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defaultThumbnail.jpg', upload_to='thumbnail'),
        ),
    ]
