# Generated by Django 4.0.5 on 2022-06-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinfo', '0003_alter_tag_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
