# Generated by Django 4.0.5 on 2022-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devinfo', '0006_tag_children_delete_tagrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tag',
            name='children',
            field=models.ManyToManyField(blank=True, to='devinfo.tag'),
        ),
    ]
